server:
  port: 9090
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    driver-class-name: oracle.jdbc.driver.OracleDriver
    username: java
    password: java12345
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 432093339127-27o4ptejbgdg4knimpbnqb4nt30sn19a.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile

  jpa:
    hibernate:
      ddl-auto: create #create update none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    defer-datasource-initialization: true
    database: oracle
    database-platform: org.hibernate.dialect.Oracle10gDialect






logging:
  level:
    org:
      springframework:
        security: debug