server:
  port: 9090
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    driver-class-name: oracle.jdbc.driver.OracleDriver
    username: java
    password: java1234
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 478099371394-9pvj09856ubmqh937ak3oqagi09n08pn.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: http://localhost:9090/oauth2/code/google
            scope:
              - email
              - profile

  jpa:
    hibernate:
      ddl-auto: create #create update none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    defer-datasource-initialization: true
    database: oracle
    database-platform: org.hibernate.dialect.Oracle10gDialect






logging:
  level:
    org:
      springframework:
        security: debug